import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { getSession } from "@auth0/nextjs-auth0";
import { redirect } from "next/navigation";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Petfinder",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const Session = await getSession();

  if (!Session) {
    redirect("/api/auth/login");
  }
  return (
    <html lang="en">
      <UserProvider>
        <body className={manrope.className}>
          <Navbar user={Session.user} />
          {children}
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
