export const{ BACK_URL, AUTH0_SECRET, AUTH0_BASE_URL, AUTH0_ISSUER_BASE_URL, AUTH0_CLIENT_ID, AUTH0_CLIENT_SECRET }= process.env;
export const NEXT_PUBLIC_AUTH0_BASE_URL = process.env.NEXT_PUBLIC_AUTH0_BASE_URL
export const NEXT_PUBLIC_BACK_URL= process.env.NEXT_PUBLIC_BACK_URL
export const NEXT_PUBLIC_QR_GEN_PASS= process.env.NEXT_PUBLIC_QR_GEN_PASS
export const NEXT_PUBLIC_TOKEN_QR_GENERATOR= process.env.NEXT_PUBLIC_TOKEN_QR_GENERATOR